---
- name: Install git RedHat/CentOS
  become: yes
  yum:
    name: git
    state: "{{ git_package_state }}"
  retries: 3
  delay: 5
  when: ansible_os_family == 'RedHat'

- name: Install git Debian/Ubuntu
  become: yes
  apt:
    name: git
    state: "{{ git_package_state }}"
    update_cache: yes
  retries: 3
  delay: 5
  when: ansible_os_family == 'Debian'

- name: Clone repository
  diff: no
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    accept_hostkey: "{{ item.accept_hostkey | default(omit) }}"
    key_file: "{{ item.key_file | default(omit)}}"
    single_branch: "{{ item.single_branch | default(omit) }}"
    track_submodules: "{{ item.track_submodules | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
  loop: "{{ git_repo }}"
